### ISSUE TITLE
Unknown location for Gene Exp Data

### ISSUE THREAD

**Issue by ambarish-prakash** [nicoleversetwo/methylation-foo#1]
Hi I tried to locate the matched Gene Expression data for this study, but only found the WGBS data set at the provided Accession number. Any idea where I could find the Gene Expression data as well?

**Comment by nicoleversetwo** [comment]
Hi there! I'm glad to hear you're interested in our dataset. Unfortunately, as the main focus of our paper was the WGBS data, the RNAseq data hasn't been publicly released yet as it is the focus of another study under review. Once published we will release the data at that time.

**Comment by ambarish-prakash** [comment]
Ah! Okay sure. Thanks for the reply :)
